const data = {
  products: [
    {
      name: 'Free shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Popular shirt',
    },
    {
      name: 'Slim shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Popular shirt',
    },
    {
      name: 'Fit  shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Popular shirt',
    },
    {
      name: 'Golf pant',
      slug: 'golf-pant',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pant',
    },
    {
      name: 'Fit pants',
      slug: 'fit-pant',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pant',
    },
    {
      name: 'Classic pants',
      slug: 'classic-pant',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 90,
      brand: '',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pant',
    },
  ],
};

export default data;